name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: CI=false npm run build

    - name: Start React App
      run: npm start &
      env:
        CI: true

    - name: Run Playwright tests
      run: npx playwright test
      env:
        HOME: /root

    - name: Archive Playwright report
      uses: actions/upload-artifact@v2
      with:
        name: playwright-report
        path: playwright-report

    - name: Archive screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: tests/screens/Documentation/FirstTest

  update-documentation:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Check out the repo (documentation branch)
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Download Playwright report
        uses: actions/download-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

      - name: Download screenshots
        uses: actions/download-artifact@v2
        with:
          name: screenshots
          path: documentation/screenshots

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Reset the gh-pages branch
        run: git reset --hard

      - name: Copy index.html to the root
        run: cp playwright-report/index.html ./index.html

      - name: Copy screenshots to the documentation folder
        run: cp -r documentation/screenshots/* ./screenshots/

      - name: Commit and push changes
        run: |
          git add index.html screenshots/
          git commit -m "Update documentation with latest screenshots"
          git push -f origin gh-pages
